### ISSUE TITLE
Task definition deprecation warning

### ISSUE THREAD

**Issue by markelliot** [palantir/baseline#3]
In Gradle 3.2:
```
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at org.gradle.api.internal.AbstractTask.leftShift(AbstractTask.java:505)
        at org.gradle.api.Task$leftShift$3.call(Unknown Source)
        at com.palantir.baseline.plugins.BaselineEclipse$_apply_closure3.doCall(BaselineEclipse.groovy:107)
...
```

**Comment by uschi2000** [comment]
Fixed for baseline in https://github.com/palantir/gradle-baseline/pull/109 . The warning still shows up for some of the plugins applied in `build.gradle`, but the warning goes away for the tests of the baseline plugins themselves.
